appender.console.type = Console
appender.console.name = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{HH:mm:ss.SSS}] %-5p [%c{1}:%L] - %m%n

# Korenski logger
rootLogger.level = INFO
rootLogger.appenderRef.stdout.ref = CONSOLE